name: Unit tests

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]
    
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run: bash -1 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          activeate-environment: environment
          environment-file: environment.yml
      - run:
        cd tests
        python -m unittest test_utils
        
  functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run: bash -1 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          activeate-environment: environment
          environment-file: environment.yml
      - run:
          cd tests
          bash -m functionaltest test_search
